Update docs.
validator-labs/docs pull request #3
Opened 2024-09-03 16:19 UTC by mattwelke

## Description
The first real update to the repo to add our docs contents.

* Remove Docusaurus and Facebook branding.
* Replace placeholder docs content with content for Validator.
* Remove `test-deploy.yml` GHA workflow. It was redundant because we have Netlify trying to build our site which is set up as a required check. If site builds are broken, PRs cannot be merged.

2024-09-03 16:56 UTC, TylerGillson reviewed
Please use orange/blue colour scheme and replace docusaurus svgs.

2024-09-03 16:56 UTC, TylerGillson commented on docs/2-validatorctl/1-download-and-install.md
> +## Install
curl command to download the latest release?

2024-09-03 16:56 UTC, TylerGillson commented on docusaurus.config.ts
> +  tagline: 'Continuous validation for environments',
"Validate any environment" ?

"Ad hoc and continuous validation for any environment" ?

2024-09-03 16:56 UTC, TylerGillson commented on src/components/HomepageFeatures/index.tsx
> +    title: 'Day 1, 2 validation',
Day 0-2 validation

2024-09-03 16:56 UTC, TylerGillson commented on docs/1-architecture.md
Please add 0-overview.md inspired by our gh organization page

2024-09-04 22:24 UTC, ahmad-ibra commented on docs/validatorctl/1-download-and-install.md
> +:::
This shouldnt be only mac/linux specific. Im pretty sure if you're on windows you can still run go install, and then based on your `GOOS` and `GOARCH` it'll setup the binary correctly (ie as a .exe and) and put it in your PATH.

2024-09-04 22:26 UTC, ahmad-ibra requested changes
overall looks really good, just the one comment about the install instructions

2024-09-04 22:44 UTC, mattwelke commented on docs/validatorctl/1-download-and-install.md
> +:::
Good point, ty. `go install` should work on Windows too.

2024-09-05 15:59 UTC, ahmad-ibra approved these changes
LGTM!

2024-09-05 16:43 UTC, merged